struct shapes;
struct board;
struct board* add_row(struct board*);
void remove_row(struct board*current);
void game();
int rand_shape();
void get_cursor(int shape);
struct board* set_board();
void print_board(struct board* last);
void rotate();
void check_board();
void update_board();