struct shapes;
struct board;
struct board* add_row(struct board*);
void remove_row(struct board*current);
void game();
int rand_shape();
void get_cursor(int shape);
struct board* set_board();
void print_board(struct board* last);
void rotate();
int check_board(int col,int size,struct board* last);
struct board* update_board(int row,int col,int size,struct board* last);
int check_lose(struct board* last);